### ISSUE TITLE
flathub verification?

### ISSUE THREAD

**Issue by qoijjj** [flathub/org.DolphinEmu.dolphin-emu#180]
Getting verification would allow an increased level of user trust.

https://discourse.flathub.org/t/how-do-you-get-a-flathub-submission-verified/3714
https://flathub.org/apps/collection/verified/1

I believe this would require the blessing of upstream devs via hosting a file.

**Comment by cpba** [comment]
This is something I would really like but I don't know how to achieve.

Are you an upstream dolphin developer?
Do you know if there'd be interest?

There is a small patch that we apply on this flatpak in order to prevent issues when users have their conf files in non-xdg paths. My aim is to ship entirely upstream dolphin, so [I've tried to upstream it](https://github.com/dolphin-emu/dolphin/pull/10556) but haven't been able to yet.

Do you have any advice or can help in any way?

**Comment by qoijjj** [comment]
@cpba I'm not a dolphin developer but the code doesn't need to be identical. All you need for verificstion is for upstream to upload a verification file behind their TLD:

https://docs.flathub.org/docs/for-app-authors/verification

**Comment by cpba** [comment]
Thank you, I see that the technical part is indeed very easy.

However, this would require the upstream project to agree to it, which is the part I don't know how to approach. Would you be able to help with it?

**Comment by qoijjj** [comment]
> Thank you, I see that the technical part is indeed very easy.
> 
> However, this would require the upstream project to agree to it, which is the part I don't know how to approach. Would you be able to help with it?

sure, here you go https://bugs.dolphin-emu.org/issues/13468

**Comment by qoijjj** [comment]
unfortunately, they declined

**Comment by starkle** [comment]
In case it helps anyone, the [PrimeHack fork](https://flathub.org/apps/io.github.shiiion.primehack) is verified on Flathub. It adds cool features to the Metroid Prime games, but it seems to emulate other games normally too.
