### ISSUE TITLE
Dolphin Version/Header mismatch.

### ISSUE THREAD

**Issue by jz5678910** [flathub/org.DolphinEmu.dolphin-emu#203]
Latest Flatpak published on July 15th has an incompatible version number and is preventing net play from being able to find sessions. 

This is what the latest Flatpak looks like:
![17211671883738385019592888718626](https://github.com/user-attachments/assets/62ebeab8-d3a6-4ab5-a536-1a537e6e1ab0)

This is what the latest build from GitHub looks like:
![17211673593426786773670480807814](https://github.com/user-attachments/assets/f0a29468-865b-49e4-894a-4e808a5f6bb8)

On a side note, would it be possible to return back to 2407 when it was released? Whether standalone or a separate branch. 
I have people I play with on windows who are on 2407 Stable and I can't play with them since we don't have a "Stable" build for Linux. 
The only builds I have access to are the one I built (2407-68) or the Flatpak (cc3ff34) and neither one can connect with 2407

If this should be separate issue please let me know.

**Comment by ColinKinloch** [comment]
For some reason my local build doesn't have this issue but the flathub stable branch does.

**Comment by cpba** [comment]
Sorry about this, we don't usually update between versions in order to
avoid this specific situation.

A exception was made this time so that users could have access to the
achievement support that came out a couple days ago.

I'll try to figure out a workaround this afternoon when I get home.

I'm the mean time, the version you want is still on flathub, you can
downgrade to it to keep playing.

The easiest way to downgrade would be to install warehouse, that's usually
more convenient than doing it from the cli.


El dc., 17 de jul. 2024, 0:26, Colin Kinloch ***@***.***> va
escriure:

**Comment by PoorPocketsMcNewHold** [comment]
Thanks for the help. 

Here's the direct command, for the version JUST before the reported 15 July build.

```
sudo flatpak update \
      --commit=b4c1decb6d71ed6c2bf448a133a746855bf37855e65790801075e64b999cb372 \
      org.DolphinEmu.dolphin-emu
```
