### ISSUE TITLE
Dolphin don't recognize the Gtk theme

### ISSUE THREAD

**Issue by MrMarukesu** [flathub/org.DolphinEmu.dolphin-emu#3]
dolphin don't apply the Gtk theme and continues using the "Windows 95" appearance.
![dolphin-flatpak-dont-themeable](https://user-images.githubusercontent.com/21296444/28604188-49966c5a-719f-11e7-9c81-17cb941cf409.png)
another flatpak app (vocal) to see that its a problem in dolphin.
![vocal-flatpak-themeable](https://user-images.githubusercontent.com/21296444/28604187-498e3fe4-719f-11e7-81e1-ce95bfe3bce3.png)

**Comment by TingPing** [comment]
Dolphin uses a bundled WxWidgets which uses Gtk2. Flathub doesn't currently package Gtk2 themes. WxWidgets does have a Gtk3 backend but it probably requires patching Dolphin to use it and even then it has iffy results IME.

**Comment by fastrizwaan** [comment]
is it possible to launch flatpak with system installed theme, the above bug is related to elementary os theme "elementary" say like "flatpak run org.DolphinEmu.dolphin-emu --theme=elementary" 

and I use https://github.com/nana-4/materia-theme a beautiful one and looks great in gnome, elementary os and budgie desktops:

here's materia light theme screenshots elementary os https://github.com/nana-4/materia-theme/issues/158
The toolbar and title bar are flat which gives a smooth look and feel

on Fedora with materia theme and dolphin:
![screenshot from 2017-10-05 13-57-42](https://user-images.githubusercontent.com/1161682/31217630-2719ae04-a9a7-11e7-9a0f-9bad70f33174.png)

Adwaita theme has titlebar and toolbar which looks raised and uneven compared to the rest of the window elements.

on Fedora with adwaita theme and dolphin:
![screenshot from 2017-10-05 13-58-02](https://user-images.githubusercontent.com/1161682/31217724-7ee970b0-a9a7-11e7-8001-6cfa869957b0.png)


TingPing, could you please add materia theme (previously flat-plat theme) and elementary theme  flatpaks so that elementary os users can have a great consistent look and feel.

Thank you.

**Comment by TingPing** [comment]
As I already answered you don't get gtk2 themes so either:

- Dolphin is patched to build wxwidgets with gtk3 (which upstream probably doesn't support)
- The runtime adds support for gtk2 themes.

**Comment by fastrizwaan** [comment]
OK got the Materia themes working with dolphin flatpaks, by copying /usr/share/themes/Materia* to ~/.themes

Here's the screenshot:
![screenshot from 2017-10-05 19-04-17](https://user-images.githubusercontent.com/1161682/31230334-43975e60-a9d3-11e7-95c8-1e87611b8b13.png)

it seems flatpak can access ~/.themes but not /usr/share/themes

TingPing, could we not allow /usr/share/themes and /usr/share/icons as read-only path for flatpaks so that themes and icons could be used by flatpaks?

Thank you.

**Comment by TingPing** [comment]
No `/usr` can't be used.

**Comment by Barthalion** [comment]
The current manifest is done lazy way and instead of building dependencies like wxgtk directly, it relies on Dolphin build system which builds it on its own if not available in the system.

You can ask upstream to set `BACKEND` to `gtk3` [here](https://github.com/dolphin-emu/dolphin/blob/master/Externals/wxWidgets3/build_wx.sh).

**Comment by fastrizwaan** [comment]
OK, opying the /usr/share/themes to ~/.themes will be a way, again a clumsy one; To pack every known theme to flatpak is not feasible. flatpak could copy the current theme to ~/.theme

Manually (again clumsy):
flatpak --copy-theme=Materia run org.Dolphin-emu.dolphin-emu 

--copy-theme =  copy the /usr/share/themes/Materia to ~/.themes

Automatic:
flatpak  --with-system-gtk-theme run org.Dolphin-emu.dolphin-emu

--with-system-gtk-theme should get the gtk theme and copy that theme to ~/.themes or some flatpak's directory

```
gsettings get org.gnome.desktop.interface gtk-theme
'Materia-light-compact'

```

Thank you.

**Comment by fastrizwaan** [comment]
Barthalion, gedit or gtk3 based  flatpaks also don't respect system installed themes, 

gedit instead uses adwaita instead of current gtk theme. which is not the expected behavior. dolphin is not using adwaita if it can't find the theme.

using gtk3 adwaita is indeed better than no theme, but IMHO, flatpaks should solve the user theme issue in a more comprehensive way.

I would like to express my thanks to you for dolphin-emu flatpak. :-)

**Comment by TingPing** [comment]
> flatpak could copy the current theme to ~/.theme

It can't because:

- Themes are incompatible between versions
- Themes (for gtk/qt) depend upon libraries

**Comment by TingPing** [comment]
I changed this to build wxwidgets manually against gtk3.
