### ISSUE TITLE
Launching Dolphin disables steam controller connected to second bluetooth adapter 

### ISSUE THREAD

**Issue by antonionardella** [flathub/org.DolphinEmu.dolphin-emu#325]
Hello,

this is what I am experiencing:

### Actual System Setup

- **Operating System**: Installed on [Bazzite Linux](https://bazzite.gg/) as flatpak using [EmuDeck](https://www.emudeck.com/) and launched through [EmulationStation](https://emulationstation.org/).  
- **Bluetooth Adapters**: 
  - TP-Link Bluetooth 4.0 Nano USB Adapter (UB500), used in passthrough mode.  
  - Trust Bluetooth USB Adapter (Broadcom BCM20702A0)
- **Configuration**:  
  - Udev rules set for passthrough.  
  - TP Link adapter whitelisted in the GUI using VID and PID.  
- **Controllers**: Using original Wii remotes and Wii MotionPlus.  

---

### All Good  

Dolphin works as expected when using the TP-Link bluetooth adapter for Wii remote passthrough.  

---

### The Issue  

The second bluetooth adapter (from Trust) connected to the system. This adapter is used to connect:  
- A Steam controller  
- A bluetooth keyboard  

Whenever Dolphin is launched, the steam controller connected to the Trust adapter is automatically disconnected and turned off. It seems Dolphin somehow also disables or interferes with this second adapter.
As soon as Dolphin is killed (using a USB connected Xbox controller), the Steam controller works again.

This issue does not occur when using other emulators like [RetroArch](https://www.retroarch.com/) or Ryujinx.  

Not sure if there is any solution to this behaviour or a workaround to make sure that the other bluetooth devices continue work.
Is there any log I can/shall share?

Thanks,
Antonio

**Comment by cpba** [comment]
I only have a single bluetooth adapter so I can't test this.

Hijacking the bluetooth adapter is how the passthrough feature works, however, dolphin shouldn't be able to also hijack the second adapter without a corresponding udev rule.

Is it possible that there's a second udev rule that grants access to the second adapter, perhaps automatically installed by emudeck or your distribution?

The way you describe it it seems like it may not actually be hijacking the second adapter, just disconnecting the devices connected to it?

> Not sure if there is any solution to this behaviour or a workaround to make sure that the other bluetooth devices continue work.

If you're only using the wiimotes in passthrough mode I'd try dropping the `allow=bluetooth` permission from the flatpak. If you don't know how, the easiest way would be to install [flatseal](https://flathub.org/apps/com.github.tchx84.Flatseal).

This permission is only needed when the "Emulate the Wii's Bluetooth adapter" option is set, passthrough mode works at the usb level and completely bypasses it. If the issue is that dolphin is disconnecting specific devices this might fix it.

I've low expectations for this particular workaround but it's worth a try, just remember to set the options back as they were if it doesn't work.

As a last option:

Entirely disabling passthrough mode is likely your best bet. By setting "Emulate the Wii's Bluetooth adapter" and then selecting "Real Wii Remote" you can pair your controller much in the same way as in passthrough mode, but with some extra perks like now savestates will work properly.

Overall this might be your best option, it's perhaps named in a confusing way but it has received a lot of development work in dolphin and is currently very solid.

**Comment by antonionardella** [comment]
Hello,

thanks for the reply.

> Entirely disabling passthrough mode is likely your best bet. By setting "Emulate the Wii's Bluetooth adapter" and then selecting "Real Wii Remote" you can pair your controller much in the same way as in passthrough mode, but with some extra perks like now savestates will work properly.

This was the solution so far.

Thanks again for the time and help!
