### ISSUE TITLE
Question About Update Frequency

### ISSUE THREAD

**Issue by Grant12311** [flathub/org.DolphinEmu.dolphin-emu#99]
Hello. I was just curious how this package handles updates, since I noticed the build currently being used is about 10 weeks old. Am I correct that beta builds are used?

**Comment by cpba** [comment]
> Am I correct that beta builds are used?

It's not set in stone, but the policy is that we update whenever there's a progress report. I believe at this point in time that's technically the same as following the beta builds, although from time to time we'll update ahead of schedule if there's a fix to some particular issue that's deemed important.

We did it this way originally because progress reports used to come out once a month and they represented visible milestones in the absence of actual releases. The progress reports have slowed down since then, it may be worth changing the policy, I'm open to suggestions.

**Comment by ColinKinloch** [comment]
NetPlay enforces matching version numbers between players, so it's best to stick with beta.

As of writing 22 NetPlay sessions exist:
* 10 are the most recent beta
* 4 are on [`5.0-15993`](https://dolphin-emu.org/download/dev/5e595616379a694789fe749e40a27ef069f0090e/) a week old alpha?
* 3 are the most recent alpha
* 3 are version `0.1.4.a` all playing "Mario Superstar Baseball"? [ProjectRio](https://github.com/CNace13/ProjectRio) apparently
* 2 are past alphas from within the last 24 hours

**Comment by Grant12311** [comment]
Ah okay. I can see why it makes sense not to update constantly.

**Comment by cpba** [comment]
Another good reason is that there are often regressions that are introduced and fixed between beta releases. These are a few of the ones talked about in the latest progress report:

- https://dolphin-emu.org/download/dev/dbaebdc585d562c25d4cf9360c8da6e078dcc1a6/
- https://dolphin-emu.org/download/dev/f0136e0eb6468908c7883cdbc978225a2c8e9626/
- https://dolphin-emu.org/download/dev/8e4155adfe22b60588ee31982cb481c7f981dbb9/
- https://dolphin-emu.org/download/dev/ddb3bad9c91300448ed28bc9f5538aaba4b2b019/

**Comment by cpba** [comment]
#103 adds a short explanation to the readme
